# Generated by Django 4.2.25 on 2025-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('report_type', models.CharField(choices=[('Dashboard', 'Dashboard Summary'), ('Employee Analytics', 'Employee Analytics'), ('Attendance Report', 'Attendance Report'), ('Performance Report', 'Performance Report'), ('Turnover Analysis', 'Turnover Analysis'), ('Custom', 'Custom Report')], max_length=30, verbose_name='report type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Scheduled', 'Scheduled'), ('Failed', 'Failed')], default='Draft', max_length=20, verbose_name='status')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('date_range_start', models.DateField(blank=True, null=True, verbose_name='date range start')),
                ('date_range_end', models.DateField(blank=True, null=True, verbose_name='date range end')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='file path')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='file size')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generated at')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='is scheduled')),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, verbose_name='schedule frequency')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='next run')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='created by')),
                ('format', models.CharField(default='pdf', max_length=10, verbose_name='format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('metric_type', models.CharField(choices=[('Employee Count', 'Employee Count'), ('Attendance Rate', 'Attendance Rate'), ('Performance Score', 'Performance Score'), ('Turnover Rate', 'Turnover Rate'), ('Leave Utilization', 'Leave Utilization'), ('Training Completion', 'Training Completion'), ('Custom', 'Custom')], max_length=30, verbose_name='metric type')),
                ('category', models.CharField(choices=[('Headcount', 'Headcount'), ('Attendance', 'Attendance'), ('Performance', 'Performance'), ('Engagement', 'Engagement'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=20, verbose_name='category')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='value')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_recorded', models.DateField(verbose_name='date recorded')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='period end')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('data_source', models.CharField(blank=True, max_length=100, verbose_name='data source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['metric_type', 'date_recorded'], name='analytics_d_metric__80129b_idx'), models.Index(fields=['category', 'department'], name='analytics_d_categor_a07e44_idx')],
            },
        ),
    ]
