# Generated by Django 4.2.25 on 2025-11-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('category', models.CharField(choices=[('General', 'General'), ('Security', 'Security'), ('Notifications', 'Notifications'), ('Integrations', 'Integrations'), ('Compliance', 'Compliance')], default='General', max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='requires restart')),
                ('data_type', models.CharField(default='string', max_length=20, verbose_name='data type')),
                ('validation_regex', models.CharField(blank=True, max_length=200, verbose_name='validation regex')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='min value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='max value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_requests', models.BooleanField(default=True, verbose_name='leave requests')),
                ('leave_approvals', models.BooleanField(default=True, verbose_name='leave approvals')),
                ('performance_reviews', models.BooleanField(default=True, verbose_name='performance reviews')),
                ('attendance_alerts', models.BooleanField(default=True, verbose_name='attendance alerts')),
                ('system_updates', models.BooleanField(default=True, verbose_name='system updates')),
                ('security_alerts', models.BooleanField(default=True, verbose_name='security alerts')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='push notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='sms notifications')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='in app notifications')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='quiet hours end')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('digest_frequency', models.CharField(default='daily', max_length=20, verbose_name='digest frequency')),
                ('batch_notifications', models.BooleanField(default=True, verbose_name='batch notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
