# Generated by Django 4.2.25 on 2025-11-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Flexible', 'Flexible')], default='Full Time', max_length=20, verbose_name='schedule type')),
                ('work_days', models.CharField(default='Monday-Friday', max_length=20, verbose_name='work days')),
                ('start_time', models.TimeField(default='09:00', verbose_name='start time')),
                ('end_time', models.TimeField(default='17:00', verbose_name='end time')),
                ('break_duration', models.PositiveIntegerField(default=60, verbose_name='break duration (minutes)')),
                ('overtime_allowed', models.BooleanField(default=True, verbose_name='overtime allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Emergency', 'Emergency Leave'), ('Other', 'Other')], max_length=20, verbose_name='leave type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('days_requested', models.PositiveIntegerField(verbose_name='days requested')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='approval date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='check in time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='check out time')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day')], default='Present', max_length=20, verbose_name='status')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='hours worked')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
