# Generated by Django 4.2.25 on 2025-11-12 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('Annual', 'Annual Review'), ('Mid Year', 'Mid Year Review'), ('Probation', 'Probation Review'), ('Project', 'Project Review'), ('Ad Hoc', 'Ad Hoc Review')], max_length=20, verbose_name='review type')),
                ('review_date', models.DateField(verbose_name='review date')),
                ('review_period_start', models.DateField(verbose_name='review period start')),
                ('review_period_end', models.DateField(verbose_name='review period end')),
                ('overall_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='overall score')),
                ('overall_rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement'), ('Unsatisfactory', 'Unsatisfactory')], max_length=20, verbose_name='overall rating')),
                ('technical_skills', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='technical skills')),
                ('communication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='communication')),
                ('teamwork', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='teamwork')),
                ('leadership', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='leadership')),
                ('initiative', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='initiative')),
                ('achievements', models.TextField(blank=True, verbose_name='achievements')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='areas for improvement')),
                ('development_plan', models.TextField(blank=True, verbose_name='development plan')),
                ('reviewer_comments', models.TextField(blank=True, verbose_name='reviewer comments')),
                ('employee_comments', models.TextField(blank=True, verbose_name='employee comments')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('employee_acknowledged', models.BooleanField(default=False, verbose_name='employee acknowledged')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='employees.employee')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('Productivity', 'Productivity'), ('Quality', 'Quality'), ('Efficiency', 'Efficiency'), ('Customer Satisfaction', 'Customer Satisfaction'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=30, verbose_name='category')),
                ('metric_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Number', 'Number'), ('Currency', 'Currency'), ('Ratio', 'Ratio'), ('Time', 'Time')], default='Percentage', max_length=20, verbose_name='metric type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='target value')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='current value')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unit')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='employees.employee')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('goal_type', models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team'), ('Department', 'Department'), ('Organizational', 'Organizational')], default='Individual', max_length=20, verbose_name='goal type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], default='Draft', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('target_completion_date', models.DateField(verbose_name='target completion date')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='actual completion date')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress percentage')),
                ('progress_notes', models.TextField(blank=True, verbose_name='progress notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
                ('performance_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='performance.performancereview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
