# Generated by Django 5.2.7 on 2025-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='role')),
                ('performance_score', models.PositiveSmallIntegerField(default=0, verbose_name='performance score')),
                ('attendance_rate', models.PositiveSmallIntegerField(default=0, verbose_name='attendance rate')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20, verbose_name='status')),
                ('initials', models.CharField(blank=True, max_length=4, verbose_name='initials')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
