# Generated by Django 5.2.7 on 2025-10-14 16:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('email_alerts', models.BooleanField(default=True, verbose_name='email alerts')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='push notifications')),
                ('weekly_reports', models.BooleanField(default=True, verbose_name='weekly reports')),
                ('performance_alerts', models.BooleanField(default=True, verbose_name='performance alerts')),
                ('attendance_alerts', models.BooleanField(default=False, verbose_name='attendance alerts')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='two factor authentication')),
                ('session_timeout', models.CharField(default='30', max_length=10, verbose_name='session timeout')),
                ('password_expiry', models.CharField(default='90', max_length=10, verbose_name='password expiry')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20, verbose_name='date format')),
                ('currency', models.CharField(default='KSH', max_length=10, verbose_name='currency')),
                ('number_format', models.CharField(default='1,000.00', max_length=20, verbose_name='number format')),
                ('week_starts_on', models.CharField(default='monday', max_length=10, verbose_name='week starts on')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='theme')),
                ('data_retention', models.CharField(default='365', max_length=10, verbose_name='data retention')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='auto backup')),
                ('export_format', models.CharField(default='csv', max_length=10, verbose_name='export format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
